[build]
  functions = "service"

[[redirects]]
  from = "/people*"
  to = "/"
  status = 200

[template.environment]
  REACT_APP_DOMAIN = "Auth0 domain"
  REACT_APP_CLIENT_ID= "Auth0 Client ID"
  REACT_APP_AUDIENCE = "Auth0 API audience"
  REACT_APP_POLICY_ROOT = "Policy root"
  POLICY_ID = "Policy ID"
  TENANT_ID = "Aserto tenant ID"
  AUTHORIZER_API_KEY = "Aserto authorizer API key"
  REACT_APP_NETLIFY = "Netlify flag must be set to NETLIFY"

[context.production]
  publish = "build/"
  command = "yarn build"
